import "./globals.css";
import type { Metadata } from "next";

import { NextIntlClientProvider } from "next-intl";
import Providers from "./providers";
import { Toaster } from "sonner";
import { BrowserRouter } from "react-router-dom";
import { ThemeProvider } from "../features/ThemeProvider";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  
  return (
    <html lang={locale}>
      <body>
        <Providers>
          <Toaster richColors position="top-right" />
          <ThemeProvider>
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
